/**
 * MCP Tools & Resources for @ux3/diagrams
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Diagrams = {
  INFO: 'diagrams.info',
} as const;

// Resource URIs — single source of truth
export const DiagramsResources = {
  DOCS: 'plugin://diagrams/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const diagramsToolHandlers = {
  [Diagrams.INFO]: async () => ({
    plugin: '@ux3/plugin-diagrams',
    version: '0.1.0',
    description: 'Mermaid diagram renderer for UX3 markdown',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const diagramsResourceHandlers = {
  [DiagramsResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# diagrams Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
