/**
 * MCP Tools & Resources for @ux3/kanban
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Kanban = {
  INFO: 'kanban.info',
} as const;

// Resource URIs — single source of truth
export const KanbanResources = {
  DOCS: 'plugin://kanban/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const kanbanToolHandlers = {
  [Kanban.INFO]: async () => ({
    plugin: '@ux3/plugin-kanban',
    version: '0.1.0',
    description: 'Kanban board widget for UX3',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const kanbanResourceHandlers = {
  [KanbanResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# kanban Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
