/**
 * MCP Tools & Resources for @ux3/calendar
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Calendar = {
  INFO: 'calendar.info',
} as const;

// Resource URIs — single source of truth
export const CalendarResources = {
  DOCS: 'plugin://calendar/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const calendarToolHandlers = {
  [Calendar.INFO]: async () => ({
    plugin: '@ux3/plugin-calendar',
    version: '0.1.0',
    description: 'Calendar widget for UX3',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const calendarResourceHandlers = {
  [CalendarResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# calendar Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
