/**
 * MCP Tools & Resources for @ux3/query-builder
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Querybuilder = {
  INFO: 'query-builder.info',
} as const;

// Resource URIs — single source of truth
export const QuerybuilderResources = {
  DOCS: 'plugin://query-builder/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const querybuilderToolHandlers = {
  [Querybuilder.INFO]: async () => ({
    plugin: '@ux3/plugin-query-builder',
    version: '0.1.0',
    description: 'Query builder widget for UX3',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const querybuilderResourceHandlers = {
  [QuerybuilderResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# query-builder Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
