/**
 * MCP Tools & Resources for @ux3/tailwind-css
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Tailwindcss = {
  INFO: 'tailwind-css.info',
} as const;

// Resource URIs — single source of truth
export const TailwindcssResources = {
  DOCS: 'plugin://tailwind-css/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const tailwindcssToolHandlers = {
  [Tailwindcss.INFO]: async () => ({
    plugin: '@ux3/plugin-tailwind-css',
    version: '0.1.0',
    description: 'Lightweight Tailwind CSS integration plugin for UX3',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const tailwindcssResourceHandlers = {
  [TailwindcssResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# tailwind-css Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
