/**
 * MCP Tools & Resources for @ux3/mcp
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Mcp = {
  INFO: 'mcp.info',
} as const;

// Resource URIs — single source of truth
export const McpResources = {
  DOCS: 'plugin://mcp/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const mcpToolHandlers = {
  [Mcp.INFO]: async () => ({
    plugin: '@ux3/plugin-mcp',
    version: '0.1.0',
    description: 'MCP client + dev server proxy for UX3',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const mcpResourceHandlers = {
  [McpResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# mcp Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
