import type { Plugin } from '../plugin/registry';

// A simple plugin that registers a `content` service using configuration
// generated by the ContentGenerator. The service exposes a `load` method that
// looks up an entry by slug or path and returns the pre-rendered HTML and
// frontmatter data.

export const ContentPlugin: Plugin = {
  name: '@ux3/content-plugin',
  version: '0.1.0',
  install(app) {
    app.registerService('content', () => {
      // service methods close over app.config so they always see up-to-date
      return {
        async load({ entry }: { entry?: string }) {
          const manifest: any = (app.config as any).content;
          if (!manifest || !Array.isArray(manifest.items)) {
            return null;
          }
          let key = entry;
          if (!key && typeof window !== 'undefined') {
            // derive from current location if not supplied
            key = window.location.pathname.replace(/^\//, '');
          }
          const find = manifest.items.find((i: any) =>
            i.slug === key || i.frontmatter.slug === key || i.frontmatter.path === key
          );
          if (!find) return null;
          return {
            html: find.html,
            frontmatter: find.frontmatter,
          };
        },
      };
    });

    // if there is a content manifest in config, register routes automatically
    const manifest: any = (app.config as any).content;
    if (manifest && Array.isArray(manifest.items)) {
      for (const item of manifest.items) {
        const routePath = item.frontmatter.path || `/${item.slug}`;
        try {
          app.registerRoute(routePath, 'content');
        } catch (_e) {
          // swallow; route may already exist
        }
      }
    }
  },
};

export default ContentPlugin;
