/**
 * MCP Tools & Resources for @ux3/browser
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Browser = {
  INFO: 'browser.info',
} as const;

// Resource URIs — single source of truth
export const BrowserResources = {
  DOCS: 'plugin://browser/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const browserToolHandlers = {
  [Browser.INFO]: async () => ({
    plugin: '@ux3/plugin-browser',
    version: '0.1.0',
    description: 'UX3 browser detection plugin - injects browser state, device info, preferences, connectivity',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const browserResourceHandlers = {
  [BrowserResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# browser Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
