/**
 * MCP Tools & Resources for @ux3/i18n
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const I18n = {
  INFO: 'i18n.info',
} as const;

// Resource URIs — single source of truth
export const I18nResources = {
  DOCS: 'plugin://i18n/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const i18nToolHandlers = {
  [I18n.INFO]: async () => ({
    plugin: '@ux3/plugin-i18n',
    version: '0.1.0',
    description: 'No description',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const i18nResourceHandlers = {
  [I18nResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# i18n Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
