/**
 * MCP Tools & Resources for @ux3/flow-editor
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Floweditor = {
  INFO: 'flow-editor.info',
} as const;

// Resource URIs — single source of truth
export const FloweditorResources = {
  DOCS: 'plugin://flow-editor/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const floweditorToolHandlers = {
  [Floweditor.INFO]: async () => ({
    plugin: '@ux3/plugin-flow-editor',
    version: '0.1.0',
    description: 'Flow editor widget for UX3',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const floweditorResourceHandlers = {
  [FloweditorResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# flow-editor Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
