/**
 * MCP Tools & Resources for @ux3/search-lunr
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Searchlunr = {
  INFO: 'search-lunr.info',
} as const;

// Resource URIs — single source of truth
export const SearchlunrResources = {
  DOCS: 'plugin://search-lunr/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const searchlunrToolHandlers = {
  [Searchlunr.INFO]: async () => ({
    plugin: '@ux3/plugin-search-lunr',
    version: '0.1.0',
    description: 'Full-text search using Lunr.js for UX3',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const searchlunrResourceHandlers = {
  [SearchlunrResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# search-lunr Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
