/**
 * MCP Tools & Resources for @ux3/oidc
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Oidc = {
  INFO: 'oidc.info',
} as const;

// Resource URIs — single source of truth
export const OidcResources = {
  DOCS: 'plugin://oidc/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const oidcToolHandlers = {
  [Oidc.INFO]: async () => ({
    plugin: '@ux3/plugin-oidc',
    version: '0.1.0',
    description: 'OIDC/OAuth2 plugin for UX3 with provider presets',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const oidcResourceHandlers = {
  [OidcResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# oidc Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
