/**
 * MCP Tools & Resources for @ux3/chat
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Chat = {
  INFO: 'chat.info',
} as const;

// Resource URIs — single source of truth
export const ChatResources = {
  DOCS: 'plugin://chat/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const chatToolHandlers = {
  [Chat.INFO]: async () => ({
    plugin: '@ux3/plugin-chat',
    version: '0.1.0',
    description: 'Chat UI widgets for UX3',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const chatResourceHandlers = {
  [ChatResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# chat Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
