/**
 * MCP Tools & Resources for @ux3/gantt
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Gantt = {
  INFO: 'gantt.info',
} as const;

// Resource URIs — single source of truth
export const GanttResources = {
  DOCS: 'plugin://gantt/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const ganttToolHandlers = {
  [Gantt.INFO]: async () => ({
    plugin: '@ux3/plugin-gantt',
    version: '0.1.0',
    description: 'Gantt chart widget for UX3',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const ganttResourceHandlers = {
  [GanttResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# gantt Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
