/**
 * MCP Tools & Resources for @ux3/report-builder
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Reportbuilder = {
  INFO: 'report-builder.info',
} as const;

// Resource URIs — single source of truth
export const ReportbuilderResources = {
  DOCS: 'plugin://report-builder/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const reportbuilderToolHandlers = {
  [Reportbuilder.INFO]: async () => ({
    plugin: '@ux3/plugin-report-builder',
    version: '0.1.0',
    description: 'Report builder widget for UX3',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const reportbuilderResourceHandlers = {
  [ReportbuilderResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# report-builder Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
