import type { PrimitiveKind } from './types.js';
import { UxRegion } from './region.js';
import { UxToggle } from './toggle.js';
import { UxAccordion } from './accordion.js';
import { UxValue } from './value.js';
import { UxSlider } from './slider.js';
import { UxInput } from './input.js';
import { UxTextarea } from './textarea.js';
import { UxForm } from './form.js';
import { UxImage, UxVideo, UxAudio } from './media.js';
import { UxWysiwyg } from './wysiwyg.js';
import { UxTabs } from './tabs.js';
import { UxMenu } from './menu.js';
import { UxPopover } from './popover.js';
import { UxTooltip } from './tooltip.js';
import { UxDrawer } from './drawer.js';
import { UxWizard } from './wizard.js';
import { UxCapture } from './capture.js';
import { UxProgress } from './progress.js';
import { UxSelect } from './select.js';
import { UxLangSwitcher, UxThemeToggle, UxNetworkStatus } from '../shell/context-tools.js';
import { UxCard } from './card.js';
import { UxAlert } from './alert.js';
import { UxSpinner } from './spinner.js';
import { UxEmptyState } from './empty-state.js';
import { UxErrorPanel } from './error-panel.js';
import { UxPagination } from './pagination.js';
import { UxBreadcrumb } from './breadcrumb.js';
import { UxCommandPalette } from './command-palette.js';
import { UxBadge } from './badge.js';
import { UxAvatar } from './avatar.js';
import { UxSkeleton } from './skeleton.js';
import { UxPage } from './page.js';
import { UxComboBox } from './combobox.js';
import { UxDatePicker } from './date-picker.js';
import { UxFileUpload } from './file-upload.js';
import { UxDropZone } from './dropzone.js';
import { UxSearchBar } from './search-bar.js';
import { UxTreeNav } from './tree-nav.js';
import { UxNotifications } from './notifications.js';
import { UxDataGrid } from './data-grid.js';
import { UxTableVirtual } from './table-virtual.js';
import { UxTable } from './table.js';
import { UxSplash } from './splash-screen.js';
import { UxRadioGroup } from './radio-group.js';
import { UxLink } from './link.js';
import { UxMegaMenu } from './mega-menu.js';
import { UxContextMenu } from './context-menu.js';

export function resolveClass(kind: PrimitiveKind): typeof HTMLElement {
  switch (kind) {
    case 'toggle': return UxToggle;
    case 'checkbox':
    case 'switch': return UxToggle;
    case 'tabs': return UxTabs;
    case 'menu': return UxMenu;
    case 'accordion': return UxAccordion;
    case 'popover': return UxPopover;
    case 'tooltip': return UxTooltip;
    case 'drawer': return UxDrawer;
    case 'wizard': return UxWizard;
    case 'value': return UxValue;
    case 'input': return UxInput;
    case 'textarea': return UxTextarea;
    case 'slider': return UxSlider;
    case 'form': return UxForm;
    case 'image': return UxImage;
    case 'video': return UxVideo;
    case 'audio': return UxAudio;
    case 'wysiwyg': return UxWysiwyg;
    case 'capture': return UxCapture;
    case 'progress': return UxProgress;
    case 'select': return UxSelect;
    case 'network-status': return UxNetworkStatus;
    case 'theme-toggle': return UxThemeToggle;
    case 'lang-switcher': return UxLangSwitcher;
    case 'card': return UxCard;
    case 'alert': return UxAlert;
    case 'spinner': return UxSpinner;
    case 'empty-state': return UxEmptyState;
    case 'error-panel': return UxErrorPanel;
    case 'pagination': return UxPagination;
    case 'breadcrumb': return UxBreadcrumb;
    case 'command-palette': return UxCommandPalette;
    case 'badge': return UxBadge;
    case 'avatar': return UxAvatar;
    case 'skeleton': return UxSkeleton;
    case 'page': return UxPage;
    case 'combobox': return UxComboBox;
    case 'date-picker': return UxDatePicker;
    case 'file-upload': return UxFileUpload;
    case 'dropzone': return UxDropZone;
    case 'search-bar': return UxSearchBar;
    case 'tree-nav': return UxTreeNav;
    case 'notifications': return UxNotifications;
    case 'data-grid': return UxDataGrid;
    case 'table-virtual': return UxTableVirtual;
    case 'table': return UxTable;
    case 'splash': return UxSplash;
    case 'radio-group': return UxRadioGroup;
    case 'link': return UxLink;
    case 'mega-menu': return UxMegaMenu;
    case 'context-menu': return UxContextMenu;
    default: return UxRegion;
  }
}
