/** Primitive type definitions */

export type PrimitiveKind = 'region' | 'toggle' | 'value' | 'input' | 'textarea' | 'slider' | 'checkbox' | 'switch' | 'form' | 'image' | 'video' | 'audio' | 'wysiwyg' | 'tabs' | 'accordion' | 'popover' | 'tooltip' | 'drawer' | 'wizard' | 'capture' | 'progress' | 'menu' | 'chart' | 'select' | 'network-status' | 'theme-toggle' | 'lang-switcher';

export interface PrimitiveDefinition {
  tag: string;
  role?: string;
  kind: PrimitiveKind;
  stateAttr?: string;
}

export const TOGGLE_KIND = new Set<PrimitiveKind>(['toggle', 'checkbox', 'switch']);

export const PRIMITIVES: PrimitiveDefinition[] = [
  { tag: 'ux-app-shell', role: 'application', kind: 'region' },
  { tag: 'ux-topbar', role: 'banner', kind: 'region' },
  { tag: 'ux-sidebar', role: 'navigation', kind: 'region' },
  { tag: 'ux-breadcrumb', role: 'navigation', kind: 'region' },
  { tag: 'ux-pagination', role: 'navigation', kind: 'value' },
  { tag: 'ux-icon-button', role: 'button', kind: 'toggle', stateAttr: 'pressed' },
  { tag: 'ux-link', role: 'link', kind: 'region' },
  { tag: 'ux-drawer', role: 'dialog', kind: 'drawer', stateAttr: 'open' },
  { tag: 'ux-tabs', role: 'tablist', kind: 'tabs' },
  { tag: 'ux-tab', role: 'tab', kind: 'toggle', stateAttr: 'selected' },
  { tag: 'ux-tab-panel', role: 'tabpanel', kind: 'region' },
  { tag: 'ux-accordion', role: 'group', kind: 'accordion', stateAttr: 'open' },
  { tag: 'ux-wizard', role: 'group', kind: 'wizard' },
  { tag: 'ux-tooltip', role: 'tooltip', kind: 'tooltip', stateAttr: 'open' },
  { tag: 'ux-menu', role: 'menu', kind: 'menu' },
  { tag: 'ux-menu-item', role: 'menuitem', kind: 'toggle', stateAttr: 'selected' },
  { tag: 'ux-select', role: 'listbox', kind: 'select' },
  { tag: 'ux-command-palette', role: 'dialog', kind: 'toggle', stateAttr: 'open' },
  { tag: 'ux-search-input', role: 'searchbox', kind: 'input' },
  { tag: 'ux-search-tags', role: 'list', kind: 'value' },
  { tag: 'ux-search-results', role: 'list', kind: 'region' },
  { tag: 'ux-table', role: 'table', kind: 'region' },
  { tag: 'ux-table-virtual', role: 'table', kind: 'region' },
  { tag: 'ux-list', role: 'list', kind: 'region' },
  { tag: 'ux-description-list', role: 'list', kind: 'region' },
  { tag: 'ux-icon', role: 'img', kind: 'region' },
  { tag: 'ux-card', role: 'article', kind: 'region' },
  { tag: 'ux-card-icon', role: 'img', kind: 'region' },
  { tag: 'ux-surface', role: 'region', kind: 'region' },
  { tag: 'ux-divider', role: 'separator', kind: 'region' },
  { tag: 'ux-badge', role: 'status', kind: 'region' },
  { tag: 'ux-avatar', role: 'img', kind: 'region' },
  { tag: 'ux-stack', kind: 'region' },
  { tag: 'ux-inline', kind: 'region' },
  { tag: 'ux-grid', kind: 'region' },
  { tag: 'ux-hero', role: 'region', kind: 'region' },
  { tag: 'ux-article', role: 'article', kind: 'region' },
  { tag: 'ux-alert', role: 'alert', kind: 'region' },
  { tag: 'ux-progress', role: 'progressbar', kind: 'progress' },
  { tag: 'ux-spinner', role: 'status', kind: 'region' },
  { tag: 'ux-skeleton', role: 'status', kind: 'region' },
  { tag: 'ux-empty-state', role: 'status', kind: 'region' },
  { tag: 'ux-error-panel', role: 'alert', kind: 'region' },
  { tag: 'ux-form', role: 'form', kind: 'form' },
  { tag: 'ux-input', role: 'textbox', kind: 'input' },
  { tag: 'ux-textarea', role: 'textbox', kind: 'textarea' },
  { tag: 'ux-checkbox', role: 'checkbox', kind: 'checkbox', stateAttr: 'checked' },
  { tag: 'ux-radio-group', role: 'radiogroup', kind: 'value' },
  { tag: 'ux-switch', role: 'switch', kind: 'switch', stateAttr: 'checked' },
  { tag: 'ux-slider', role: 'slider', kind: 'slider' },
  { tag: 'ux-form-errors', role: 'alert', kind: 'region' },
  { tag: 'ux-image', role: 'img', kind: 'image' },
  { tag: 'ux-image-panel', role: 'img', kind: 'toggle', stateAttr: 'open' },
  { tag: 'ux-image-capture', role: 'button', kind: 'capture' },
  { tag: 'ux-video', role: 'group', kind: 'video' },
  { tag: 'ux-video-capture', role: 'button', kind: 'capture' },
  { tag: 'ux-audio', role: 'group', kind: 'audio' },
  { tag: 'ux-audio-capture', role: 'button', kind: 'capture' },
  { tag: 'ux-chart-line', role: 'img', kind: 'chart' },
  { tag: 'ux-chart-bar', role: 'img', kind: 'chart' },
  { tag: 'ux-chart-donut', role: 'img', kind: 'chart' },
  { tag: 'ux-chat-messenger', role: 'log', kind: 'region' },
  { tag: 'ux-chat-thread-list', role: 'list', kind: 'region' },
  { tag: 'ux-chat-messages', role: 'log', kind: 'region' },
  { tag: 'ux-chat-bubble', role: 'article', kind: 'region' },
  { tag: 'ux-chat-composer', role: 'form', kind: 'form' },
  { tag: 'ux-chat-roster', role: 'list', kind: 'region' },
  { tag: 'ux-popover', role: 'dialog', kind: 'popover', stateAttr: 'open' },
  { tag: 'ux-hover-panel', role: 'dialog', kind: 'tooltip', stateAttr: 'open' },
  { tag: 'ux-splash', role: 'status', kind: 'region' },
  { tag: 'ux-splash-screen', role: 'status', kind: 'region' },
  { tag: 'ux-wysiwyg', role: 'textbox', kind: 'wysiwyg' },
  { tag: 'ux-content', role: 'region', kind: 'region' },
  { tag: 'ux-chart-line-legend', role: 'list', kind: 'region' },
  { tag: 'ux-network-status', role: 'status', kind: 'network-status' },
  { tag: 'ux-theme-toggle', role: 'switch', kind: 'theme-toggle', stateAttr: 'checked' },
  { tag: 'ux-lang-switcher', role: 'listbox', kind: 'lang-switcher' },
];

export const DEF_BY_TAG = new Map(PRIMITIVES.map((def) => [def.tag, def]));
