/**
 * MCP Tools & Resources for @ux3/skeleton
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Skeleton = {
  INFO: 'skeleton.info',
} as const;

// Resource URIs — single source of truth
export const SkeletonResources = {
  DOCS: 'plugin://skeleton/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const skeletonToolHandlers = {
  [Skeleton.INFO]: async () => ({
    plugin: '@ux3/plugin-skeleton',
    version: '0.1.0',
    description: 'Scaffolding plugin for UX3 - generates projects, views, services, and other artifacts from templates',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const skeletonResourceHandlers = {
  [SkeletonResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# skeleton Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
