import { writeFile } from 'node:fs/promises';
import { Builder } from '@flatbuffers/flatbuffers';
import { contentEntries, promptTemplates } from './content-data.js';

const OUT_TS = new URL('./built-index.ts', import.meta.url);
const OUT_BIN = new URL('../dist/onnx-index.bin', import.meta.url);

function buildFlatBufferPayload(): Uint8Array {
  const payload = JSON.stringify({ entries: contentEntries, prompts: promptTemplates });
  const builder = new Builder(1024);
  const payloadOffset = builder.createString(payload);
  builder.startObject(1);
  builder.addFieldOffset(0, payloadOffset, 0);
  const root = builder.endObject();
  builder.finish(root);
  return builder.asUint8Array();
}

function base64FromBytes(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i += 1) {
    binary += String.fromCharCode(bytes[i]);
  }
  return Buffer.from(binary, 'binary').toString('base64');
}

async function main() {
  const bytes = buildFlatBufferPayload();
  const base64 = base64FromBytes(bytes);
  const tsSource = `// Generated by src/build-index.ts
export const ONNX_INDEX_BASE64 = ${JSON.stringify(base64)};
`;

  await writeFile(OUT_TS, tsSource, 'utf-8');
  await writeFile(OUT_BIN, bytes, 'binary');
  console.log(`Generated ONNX index: ${OUT_TS.pathname}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
