/**
 * MCP Tools & Resources for @ux3/primitives
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Primitives = {
  INFO: 'primitives.info',
} as const;

// Resource URIs — single source of truth
export const PrimitivesResources = {
  DOCS: 'plugin://primitives/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const primitivesToolHandlers = {
  [Primitives.INFO]: async () => ({
    plugin: '@ux3/plugin-primitives',
    version: '0.1.0',
    description: 'Filter builder widget for UX3',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const primitivesResourceHandlers = {
  [PrimitivesResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# primitives Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
