/**
 * MCP Tools & Resources for @ux3/store
 * 
 * Auto-generated by Phase 4 migration generator.
 * Update tool/resource names and handlers as needed.
 */

// Tool names — single source of truth
export const Store = {
  INFO: 'store.info',
} as const;

// Resource URIs — single source of truth
export const StoreResources = {
  DOCS: 'plugin://store/docs',
} as const;

// Tool handlers — dispatched via callTool()
export const storeToolHandlers = {
  [Store.INFO]: async () => ({
    plugin: '@ux3/plugin-store',
    version: '0.1.0',
    description: 'Storage plugin for UX3 with support for localStorage, IndexedDB, remote sync, and hybrid patterns',
    // TODO: Add plugin-specific information
  }),
} as const satisfies Record<string, (args: any) => Promise<any>>;

// Resource handlers — dispatched via readResource()
export const storeResourceHandlers = {
  [StoreResources.DOCS]: async () => {
    // TODO: Return plugin documentation (markdown)
    return '# store Documentation\n\nPlugin documentation goes here.';
  },
} as const satisfies Record<string, () => Promise<string>>;
