routes:
  - path: /
    view: index
  - path: /organization
    view: organization
  - path: /membership
    view: membership
  - path: /subscription
    view: subscription
  - path: /audit-log
    view: audit-log
